# Generated by Django 4.0.1 on 2022-01-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_module_resource_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
