# Generated by Django 4.0.1 on 2022-01-16 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_progress_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.module'),
        ),
    ]
